// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Travail1_Partie_4.Models;

namespace Travail1_Partie_4.Models
{
    public partial class Bd_ReseauContext
    {
        private IBd_ReseauContextProcedures _procedures;

        public virtual IBd_ReseauContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Bd_ReseauContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBd_ReseauContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class Bd_ReseauContextProcedures : IBd_ReseauContextProcedures
    {
        private readonly Bd_ReseauContext _context;

        public Bd_ReseauContextProcedures(Bd_ReseauContext context)
        {
            _context = context;
        }

        public virtual async Task<List<RechercherPieceParNumeroIndustrieResult>> RechercherPieceParNumeroIndustrieAsync(string noIndustrie, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "noIndustrie",
                    Size = 200,
                    Value = noIndustrie ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<RechercherPieceParNumeroIndustrieResult>("EXEC @returnValue = [dbo].[RechercherPieceParNumeroIndustrie] @noIndustrie = @noIndustrie", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
