// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Travail1_Partie_4.Models;

namespace Travail1_Partie_4.Models
{
    public partial interface IBd_ReseauContextProcedures
    {
        Task<List<RechercherPieceParNumeroIndustrieResult>> RechercherPieceParNumeroIndustrieAsync(string noIndustrie, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
