// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Travail1_Partie_4.Models
{
    public partial class RechercherPieceParNumeroIndustrieResult
    {
        [StringLength(200)]
        public string numeroIndustrie { get; set; }
        [StringLength(200)]
        public string description { get; set; }
    }
}
