// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Travail_2_BD.Models
{
    public partial class RechercherProjetsParNumeroIndustrieResult
    {
        public int id_projet { get; set; }
        [StringLength(200)]
        public string nom_projet { get; set; }
        [StringLength(200)]
        public string description_projet { get; set; }
    }
}
