// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travail_2_BD.Models;

[Table("tbl_inventaireNonAssigne")]
[Index("NoPiece", Name = "UQ__tbl_inve__68720D8FFF80C18B", IsUnique = true)]
public partial class TblInventaireNonAssigne
{
    [Key]
    [Column("no_inventaireNonAssigne")]
    public int NoInventaireNonAssigne { get; set; }

    [Column("no_piece")]
    public int? NoPiece { get; set; }

    [Column("quantite")]
    public int? Quantite { get; set; }
}