// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Travail_2_BD.Models;

[Keyless]
public partial class VueListerQuantitePrevueProjet
{
    [Column("id_stock")]
    public int IdStock { get; set; }

    [Column("id_projet")]
    public int IdProjet { get; set; }

    [Column("nom_projet")]
    [StringLength(200)]
    public string NomProjet { get; set; }

    [Column("id_piece")]
    public int IdPiece { get; set; }

    [Column("nom_piece")]
    [StringLength(200)]
    public string NomPiece { get; set; }

    [Column("quantite_prevu")]
    public int? QuantitePrevu { get; set; }
}